spring:
  application:
    name: wms-core-engine

  main:
    # Desliga o banner ASCII do Spring Boot no console/logs
    banner-mode: "off"

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/wms_db
    username: postgres
    password: postgrespassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Deixa o Flyway gerenciar a estrutura do banco
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    repair-on-migrate: true
    validate-on-migrate: false

server:
  port: 8080
  # 1. Suprime o cabeçalho "Server: Apache-Coyote" / Tomcat
  server-header: ""
  error:
    # 2. Desativa a Whitelabel e suprime rastros de exceção em respostas de erro
    whitelabel:
      enabled: false
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
  servlet:
    session:
      cookie:
        # 3. Renomeia o cookie de sessão para não usar JSESSIONID
        name: APP_SESSION_ID